spring:
  application:
    name: commercehub

  datasource:
    url: jdbc:postgresql://localhost:5432/commercehub
    username: ${DB_USERNAME:commercehub}
    password: ${DB_PASSWORD:commercehub_dev}
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#      connection-timeout: 30000

  jpa:
    hibernate:
     ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# about spring actuator health,info
management:
  endpoints:
    web:
      exposure:
        include: health,info
#        include: "*"
  endpoint:
    health:
      show-details: when_authorized
#      show-details: always

server:
  port: 8080